region = "us-east-1"
bucket_name = "mynewbucket3108202494800"
bucket_tag = "New_S3_bucket"
object_owner = "BucketOwnerPreferred"
access_control = "public-read"
index = "index.html"
error = "error.html"
content_type = "text/html"